depot/config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products do
    get :who_bought, on: :member
  end

  root 'store#index', :as => 'store'

end

depot/app/views/layouts/application.html.slim
doctype html

html
  head
    title PragProg Books Online Store
    = stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body class=controller.controller_name
    #banner
      = image_tag("logo.png")
      = @page_title || "Pragmatic Bookshelf"
    #columns
      #side
        - if @cart
          = hidden_div_if(@cart.line_items.empty?, id: 'cart') { render @cart }
          /#cart = render @cart

        ul
          li
            = link_to 'Home', store_path
          li
            a href="http://www.../faq" Questions
          li
            a href="http://www.../news" News
          li
            a href="http://www.../contact" Contact

        - if session[:user_id]
          ul
            li = link_to 'Orders', orders_path
            li = link_to 'Products', products_path
            li = link_to 'Users', users_path
          = button_to 'Logout', logout_path, method: :delete

        = Time.now.strftime("%m/%d/%y - %I:%M%p")
      #main
        = yield